services:
  - type: web
    name: pravah-house-price-api
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python train_model.py
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,https://pravah-workshop-n8zn.vercel.app,https://pravah-homes.vercel.app
      - key: PYTHON_VERSION
        value: "3.11.0"
